"""add detailed attendance tracking fields to live attendance table

Revision ID: 7dfe24ee7aca
Revises: 0001_initial_postgres
Create Date: 2026-04-04 12:53:19.308810

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7dfe24ee7aca'
down_revision: Union[str, Sequence[str], None] = '0001_initial_postgres'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('live_attendance_table', sa.Column('Attended_Live', sa.Boolean(), nullable=True))
    op.add_column('live_attendance_table', sa.Column('Watched_Recording', sa.Boolean(), nullable=True))
    op.add_column('live_attendance_table', sa.Column('Is_Present', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('live_attendance_table', 'Is_Present')
    op.drop_column('live_attendance_table', 'Watched_Recording')
    op.drop_column('live_attendance_table', 'Attended_Live')
    # ### end Alembic commands ###
